{{- if and .Values.backend.enabled .Values.backend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scrummate.fullname" . }}-backend-pdb
  labels:
    {{- include "scrummate.backend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.backend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "scrummate.backend.selectorLabels" . | nindent 6 }}
---
{{- end }}
{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "scrummate.fullname" . }}-frontend-pdb
  labels:
    {{- include "scrummate.frontend.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "scrummate.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
