{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrummate.fullname" . }}-backend
  labels:
    {{- include "scrummate.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "scrummate.backend.selectorLabels" . | nindent 4 }}
---
{{- end }}
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrummate.fullname" . }}-frontend
  labels:
    {{- include "scrummate.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "scrummate.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
