# Copyright (c) 2025 Telefonaktiebolaget LM Ericsson
# ScrumMate Development Environment Kustomization

apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: scrummate-dev
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: scrummate-repo
  path: "./gitops/environments/dev"
  prune: true
  wait: true
  timeout: 8m
  targetNamespace: scrummate-dev
  dependsOn:
    - name: scrummate-app
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: scrummate-frontend
      namespace: scrummate-dev
    - apiVersion: apps/v1
      kind: Deployment
      name: scrummate-backend
      namespace: scrummate-dev
  postBuild:
    substitute:
      environment: "dev"
      replicas: "1"
      cpu_limit: "500m"
      memory_limit: "512Mi"
      storage_size: "10Gi"
