apiVersion: v2
name: scrummate
description: A cloud-native Agile work tracking application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - agile
  - scrum
  - tracking
  - productivity
  - spring-boot
  - react
home: https://github.com/ericsson/scrummate
sources:
  - https://github.com/ericsson/scrummate
maintainers:
  - name: ScrumMate Team
    email: scrummate-team@ericsson.com
dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: kube-prometheus-stack
    version: "55.5.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled
annotations:
  category: Productivity
  licenses: Apache-2.0
